name: csv_to_json
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.5

dependencies:
  args: ^2.5.0
  csv: ^6.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
